CREATE TABLE PRODUTO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(150),
	DESCRICAO VARCHAR(500),
	PRECO BIGINT,
	QTD_DISPONIVEL BIGINT
);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ('CERVEJA SKOL', 'CERVEJA DE MILHO 5%', 5.5, 100);