CREATE TABLE CATEGORIA (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(150),
	DESCRICAO VARCHAR(500)
);

INSERT INTO CATEGORIA (NOME, DESCRICAO)
VALUES ('BEBIDAS ALCOÓLICAS', 'BEBIDAS COM TEOR ALCOÓLICO EM SUA PRODUÇÃO E COMPOSIÇÃO');

